version: '3'

services:
  build:
    build: .
    command: bundle exec jekyll build
    volumes:
      - .:/app
  buildincremental:
    build: .
    command: bundle exec jekyll b --incremental
    volumes:
      - .:/app
  serve:
    build: .
    command: bundle exec jekyll serve --host 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - .:/app


# When you specify a command for a service in the Docker Compose file, it overrides the CMD instruction in the Dockerfile. So in your case, the command specified in the serve service will be used instead of the CMD instruction in the Dockerfile when you run the container.
# However, it's still a good idea to include the CMD instruction in the Dockerfile as a fallback in case the command is not specified in the Docker Compose file.